//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccclient_iface_v1.h>
#include <public/ccserver_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	TEDROOMBool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[15];
	TEDROOMBool	comp2QueueNodesMarks[15];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	TEDROOMBool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[15];
	TEDROOMBool	comp3QueueNodesMarks[15];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	TEDROOMBool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[15];
	TEDROOMBool	comp4QueueNodesMarks[15];
 
	//!Messages Memory of component comp5
	CEDROOMMessage	comp5Messages[10];
	TEDROOMBool	comp5MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp5QueueNodes[15];
	TEDROOMBool	comp5QueueNodesMarks[15];
 
	//!Messages Memory of component comp7
	CEDROOMMessage	comp7Messages[10];
	TEDROOMBool	comp7MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp7QueueNodes[14];
	TEDROOMBool	comp7QueueNodesMarks[14];
 
	//!Messages Memory of component comp8
	CEDROOMMessage	comp8Messages[10];
	TEDROOMBool	comp8MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp8QueueNodes[14];
	TEDROOMBool	comp8QueueNodesMarks[14];
 
	//!Messages Memory of component comp9
	CEDROOMMessage	comp9Messages[10];
	TEDROOMBool	comp9MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp9QueueNodes[15];
	TEDROOMBool	comp9QueueNodesMarks[15];
 
	//!Messages Memory of component comp10
	CEDROOMMessage	comp10Messages[10];
	TEDROOMBool	comp10MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp10QueueNodes[15];
	TEDROOMBool	comp10QueueNodesMarks[15];
 
	//!Messages Memory of component comp11
	CEDROOMMessage	comp11Messages[10];
	TEDROOMBool	comp11MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp11QueueNodes[15];
	TEDROOMBool	comp11QueueNodesMarks[15];
 
	//!Messages Memory of component comp12
	CEDROOMMessage	comp12Messages[10];
	TEDROOMBool	comp12MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp12QueueNodes[15];
	TEDROOMBool	comp12QueueNodesMarks[15];
 
	public:
 
	CCClient::CEDROOMMemory comp2Memory;
	CCClient::CEDROOMMemory comp3Memory;
	CCClient::CEDROOMMemory comp4Memory;
	CCClient::CEDROOMMemory comp5Memory;
	CCServer::CEDROOMMemory comp7Memory;
	CCServer::CEDROOMMemory comp8Memory;
	CCClient::CEDROOMMemory comp9Memory;
	CCClient::CEDROOMMemory comp10Memory;
	CCClient::CEDROOMMemory comp11Memory;
	CCClient::CEDROOMMemory comp12Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[8];
 
	CCClient   * mp_comp2;
	CCClient   * mp_comp3;
	CCClient   * mp_comp4;
	CCClient   * mp_comp5;
	CCServer   * mp_comp7;
	CCServer   * mp_comp8;
	CCClient   * mp_comp9;
	CCClient   * mp_comp10;
	CCClient   * mp_comp11;
	CCClient   * mp_comp12;
 
 
//!Set Components
 
	void SetComponents(CCClient   *p_comp2,
							CCClient   *p_comp3,
							CCClient   *p_comp4,
							CCClient   *p_comp5,
							CCServer   *p_comp7,
							CCServer   *p_comp8,
							CCClient   *p_comp9,
							CCClient   *p_comp10,
							CCClient   *p_comp11,
							CCClient   *p_comp12);
 
 
//Signal Conversion
 
	static TEDROOMSignal C8Server2_PpService4__C5Client4_PpServReq(TEDROOMSignal signal);
	static TEDROOMSignal C5Client4_PpServReq__C8Server2_PpService4(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C8Server2_PpService3__C4Client3_PpServReq(TEDROOMSignal signal);
	static TEDROOMSignal C4Client3_PpServReq__C8Server2_PpService3(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C8Server2_PpService2__C3Client2_PpServReq(TEDROOMSignal signal);
	static TEDROOMSignal C3Client2_PpServReq__C8Server2_PpService2(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C8Server2_PpService1__C2Client1_PpServReq(TEDROOMSignal signal);
	static TEDROOMSignal C2Client1_PpServReq__C8Server2_PpService1(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C12Client8_PpServReq__C7Server1_PpService4(TEDROOMSignal signal);
	static TEDROOMSignal C7Server1_PpService4__C12Client8_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C11Client7_PpServReq__C7Server1_PpService3(TEDROOMSignal signal);
	static TEDROOMSignal C7Server1_PpService3__C11Client7_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C10Client6_PpServReq__C7Server1_PpService2(TEDROOMSignal signal);
	static TEDROOMSignal C7Server1_PpService2__C10Client6_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C9Client5_PpServReq__C7Server1_PpService1(TEDROOMSignal signal);
	static TEDROOMSignal C7Server1_PpService1__C9Client5_PpServReq(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CCClient   * mp_comp2;
	CCClient   * mp_comp3;
	CCClient   * mp_comp4;
	CCClient   * mp_comp5;
	CCServer   * mp_comp7;
	CCServer   * mp_comp8;
	CCClient   * mp_comp9;
	CCClient   * mp_comp10;
	CCClient   * mp_comp11;
	CCClient   * mp_comp12;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CCClient   *p_comp2,
					CCClient   *p_comp3,
					CCClient   *p_comp4,
					CCClient   *p_comp5,
					CCServer   *p_comp7,
					CCServer   *p_comp8,
					CCClient   *p_comp9,
					CCClient   *p_comp10,
					CCClient   *p_comp11,
					CCClient   *p_comp12);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CCClient::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCClient::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CCClient::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
	CCClient::CEDROOMMemory 		* GetComp5Memory(){return &systemMemory.comp5Memory;}
	CCServer::CEDROOMMemory 		* GetComp7Memory(){return &systemMemory.comp7Memory;}
	CCServer::CEDROOMMemory 		* GetComp8Memory(){return &systemMemory.comp8Memory;}
	CCClient::CEDROOMMemory 		* GetComp9Memory(){return &systemMemory.comp9Memory;}
	CCClient::CEDROOMMemory 		* GetComp10Memory(){return &systemMemory.comp10Memory;}
	CCClient::CEDROOMMemory 		* GetComp11Memory(){return &systemMemory.comp11Memory;}
	CCClient::CEDROOMMemory 		* GetComp12Memory(){return &systemMemory.comp12Memory;}
 
};
#endif
