//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccserver_iface_v1.h>
#include <public/ccserver_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
#include <public/ccclient_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	CCClient	comp2(2, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
	CCClient	comp3(3, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
	CCClient	comp4(4, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
	CCClient	comp5(5, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp5Memory());
	CCServer	comp7(7, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp7Memory());
	CCServer	comp8(8, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp8Memory());
	CCClient	comp9(9, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp9Memory());
	CCClient	comp10(10, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp10Memory());
	CCClient	comp11(11, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp11Memory());
	CCClient	comp12(12, 15, EDROOMprioNormal, 1024, systemDeployment.GetComp12Memory());
 
	systemDeployment.Config(&comp2, &comp3, &comp4, &comp5, &comp7, &comp8, &comp9, &comp10, &comp11, &comp12);
 
	systemDeployment.Start();
 
	;
 
}
